url: "https://cs.umanitoba.ca"
baseurl: "/~wics"
sitename: "UM WICS"
locale: "en-US"
permalink: pretty
github: [metadata]

# Generates a sitemap.xml file
plugins:
    - jekyll-sitemap

collections:
    pages: # Keep the root clean organizing all pages into _pages
        output: true
        permalink: /:path/
    co-op-companies:

exclude:
    - README.md
    - scripts
